In [1]:
# Método de Newton-Raphson
# Ejemplo 1 (Burden ejemplo 1 p.51/pdf.61)

import numpy as np

# INGRESO
fx  = lambda x: np.exp(-x) + x/5 - 1
dfx = lambda x: -np.exp(-x) + 1/5

x0 = 2
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[2.0000e+00 9.1858e+00 7.1858e+00]
 [9.1858e+00 4.9973e+00 4.1884e+00]
 [4.9973e+00 4.9651e+00 3.2209e-02]
 [4.9651e+00 4.9651e+00 1.8351e-05]]
raiz en:  4.965114231750363
con error de:  1.8351145969042193e-05
