# Física Moderna

## Práctica 1. Python para físicos

En esta práctica haremos uso de las principales herramientas del lenguaje Python.

Procedimiento. Abra este archivo [Practi-01.ipynb] con Jupyter. Una vez que esté leyendo esto en Jupyter, realice los ejercicios  propuestos. 

## 1. Introducción

Instrucciones básicas: Cada cuadro que aparece para editar, como éste:

In [10]:
print("hola mundo")

hola mundo


Es un cuadro que permite la introducción de código Python y para ejecutar solo tenemos que presionar 'shift + enter' (en las prácticas se va obviar pedir que se presionen estas teclas). La primera función de python que vamos a usar es

esta función imprime en pantalla en valor de la variable a. Usemosla: primero defina una variable llamada 'yo' cuyo contenido sea su nombre (recuerde que las cadenas en python se definen entre comillas Ej. "cadena").

In [11]:
yo = 'Maximiliano Vaca Montejano'

Imprima el valor de la variable yo usando la función print. Puede averiguar cómo se usa esta función tecleando: print?

In [12]:
print(yo)

Maximiliano Vaca Montejano


En python las variables son dinámicas, es decir no tienen un tipo definido. De esta manera podemos cambiarle el valor a la variable yo y ponerle por ejemplo un valor numérico. Asigne su edad en años a la variable yo.

In [13]:
yo = 20

Existe tres tipos principales de variables que usamos en cálculos físicos, a saber enteros, flotantes y complejos. Defina una variable llamada entero con valor igual al año en que ingresó a la universidad; una variable llamada flotante con valor cercano a pi (con los decimales que se acuerde) y una variable llamada complejo cuya parte real sea el valor de la variable entero y la parte imaginaria el valor de flotante (para de denotar la parte imaginaria se pone j después del número) .

In [14]:
entero = 2020

In [15]:
flotante = 3.1416

In [16]:
complejo = 2020 + 3.1426j

Existen convertidores entre estos tipos de variable, estas funciones son: int, float y complex. Averigue con funcionan, preguntando aquí en jupyter, para esto use el simbolo ? después de la funcion.

**int** : *"Convert a number or string to an integer, or return 0 if no arguments are given. If x is a number, return x.__int__(). For floating point numbers, this truncates towards zero."*

**float** : *"Convert a number or string to an integer, or return 0 if no arguments are given. If x is a number, return x.__int__(). For floating point numbers, this truncates towards zero."*

**complex** : *"Create a complex number from a real part and an optional imaginary part. This is equivalent to (real + imag\*1j) where imag defaults to 0."*

Operaciones Aritméticas:

Existen otras operaciones útiles:

apliquemos las siguiente operaciones, considere un paralelepipedo de largo 5.3 ancho 4 y alto 10. Encuentre el area de la cara más pequeña.

In [17]:
area1 = 5.3 * 4
area2 = 4 * 10 
area3 = 5.3 * 10 
areas = [area1, area2, area3]
areas.sort()
print('el area mas pequeña del paralelepipedo tiene un valor de', areas[0], 'unidades')
print('le sigue', areas[1], 'y luego', areas[2])


el area mas pequeña del paralelepipedo tiene un valor de 21.2 unidades
le sigue 40 y luego 53.0


In [18]:
volumenP = areas[0] * areas[1] * areas[2]
print('el volumen del paralelepipedo es de', volumenP, 'unidades')
volumenC = areas[0] **2
print('el volumen del cubo es de', volumenC, 'unidades')
diferencia = volumenP - volumenC
print('la diferencia entre los dos volumenes es de', diferencia, 'unidades')

el volumen del paralelepipedo es de 44944.0 unidades
el volumen del cubo es de 449.44 unidades
la diferencia entre los dos volumenes es de 44494.56 unidades


Si se asigna el resultado de una operación a una variable esta tendrá el tipo más general de las variables involucradas en la operación. Ejemplifique lo anterior.

In [19]:
general1 = 123 + 12.3
print(type(general1))

general2 = 123 + 12.3 + (12 + 34j)
print(type(general2))

print('en el primer caso, el tipo float es mas general que el int. En el segundo caso, el tipo complex es aun mas general que el float')

<class 'float'>
<class 'complex'>
en el primer caso, el tipo float es mas general que el int. En el segundo caso, el tipo complex es aun mas general que el float


** Como la longitud es un flotante, la diferecia de volumen "difvol" tambien es flotante **

¿Que hace la siguiente sentencia?:

** Al valor almacenado de x se le suma 1, y ese sera el nuevo valor de x **

Averiguelo probando aquí:

** Le asignamos un valor al azar, digamos 1 **

In [20]:
x = 1

In [21]:
x = x+1

In [22]:
print(x)

2


y escriba su conclusión aquí:

el resultado es que x tiene un valor de 2

 A continuación mostraremos algunos modificadores, después de mostrarlos usted debe encontrar su función experimentado y después  escribir su conclusión en la celda de escritura.

In [23]:
print(x)

2


In [24]:
x += 2

In [25]:
print(x)

4


Sirve para: Al valor almacenado en la variable se le suma el numero que se ponga despues de "+=", lo que resulta mas practico que escribir "x = x+1" por ejemplo

In [26]:
print(x)

4


In [27]:
x -= 2

In [28]:
print(x)

2


Sirve para: Al valor almacenado en la variable se le resta el numero que se ponga despues de "-=", lo que resulta mas practico que escribir "x = x-1" por ejemplo

In [29]:
x *= 8

In [30]:
print(x)

16


Sirve para: Al valor almacenado en la variable se le multiplica por el numero que se ponga despues de "*=", lo que resulta mas practico que escribir "x = x\*5" por ejemplo, en caso de querer multiplicar por 5

In [31]:
x /= 4

In [32]:
print(x)

4.0


Sirve para: Al valor almacenado en la variable se le divide entre el numero que se ponga despues de "/=", lo que resulta mas practico que escribir "x = x\5" por ejemplo, si quisieramos dividir x entre 5

In [33]:
x //= 2.5

In [34]:
print(x)

1.0


Sirve para tomar la parte entera de la division de x por 3.4

In [35]:
x = 14
y = 25

In [36]:
print(x,y)

14 25


In [37]:
x,y = y,x

In [38]:
print(x,y)

25 14


In [39]:
print(x)
print(y)

25
14


R= intercambia el valor de las variables *x* y *y*

Para preguntar al usuario un valor se puede usar la función input, se usa así

Averigue cuál es el tipo de la variable edad en el ejemplo anterior.

#### Pelota lanzada desde una torre.

Considere una pelota lanzada desde una torre de altura $h$. Tiene velocidad inicial cero y se acelera hacia abajo debido a la gravedad (que tomamos como $g=9.81$ $ms^-1$). Ignorando la fricción del aire, encuentre la altura de la pelota a un tiempo $t$.

Para solucionar este problema escribiremos un programa que pida al usuario la altura del edificio y el tiempo al que quiere saber la altura de la pelota e imprima al altura de la pelota a ese tiempo

In [40]:
g = 9.81

h0 = int(input('ingresa la altura de la torre en metros: '))
t = int(input('ingresa el tiempo en segundos al cual que quieres saber la altura: '))

h1 = h0 - g * (t*t) / 2

if h1 < 0: h1 = 0

print('La altura de la pelota al tiempo', t, 'segundos despues de dejarse caer es de', h1, 'metros')

Usando su código anterior, encuentre la altura de una pelota que es lanza desde 100 metros a t=1 s. Escriba su resultado.

In [1]:
g = 9.81

h0 = 100
t = 1

h1 = h0 - g * (t*t) / 2

if h1 < 0: h1 = 0

print('La altura de la pelota al tiempo', t, 'segundos despues de dejarse caer es de', h1, 'metros')

La altura de la pelota al tiempo 1 segundos despues de dejarse caer es de 95.095 metros


Usando su código anterior, encuentre la altura de una pelota que es lanza desde 200 metros a t=10 s. Escriba su resultado.

In [ ]:
g = 9.81

h0 = 200
t = 10

h1 = h0 - g * (t*t) / 2

if h1 < 0: h1 = 0

print('La altura de la pelota al tiempo', t, 'segundos despues de dejarse caer es de', h1, 'metros')

La altura de la pelota al tiempo 10 segundos despues de dejarse caer es de 0 metros


Explique su resultado.

Para arreglar su programa vamos a usar el condicional if. Este funciona de la siguiente manera:

donde expresion refiere a una condición, para estas generalmente se usan los siguientes operadores ==, <, > <=, >=, !=

Note que en python no necesitamos decir dónde termina el codigo para cada condicional, esto se especifica con la identación. Usando el condicional if reescriba su programa para la caída de la pelota para que no arroje números negativos e informe al usuario.

In [ ]:
g = 9.81

h0 = int(input('ingresa la altura de la torre en metros: '))
t = int(input('ingresa el tiempo en segundos al cual que quieres saber la altura: '))

h1 = h0 - g * (t*t) / 2

if h1 == 0:
    print('La pelota cayo justo en el piso al tiempo', t, 'segundos')
elif h1 < 0: 
    print('El tiempo ingresado en segundos excede el necesario para que la pelota llegue al piso')
else: 
    print('La altura de la pelota al tiempo', t, 'segundos despues de dejarse caer es de', h1, 'metros')


#### Ciclos en Python

En python hay solo dos tipos de loops o ciclos y son los ciclos while y los ciclos for. El primero es:

El bloque de código se ejecutará mientras se cumpla la condición (mientras sea verdadera). Escriba un codigo que sume todos los numeros pares del 1 al 500 y que imprima el resultado.

In [2]:
s = 0
i=0

while i < 500:
    i+=1  
    if i%2 ==0:
        s += i  

print('la suma todos los numeros pares del 1 al 500 es',s)

#comprobando 
s = 0
i=0
for i in range(1,501):
    if i%2 ==0:
        s += i
print('la suma todos los numeros pares del 1 al 500 es',s)

la suma todos los numeros pares del 1 al 500 es 62750
la suma todos los numeros pares del 1 al 500 es 62750


El otro tipo de ciclo es el que ofrece for. Este tipo de ciclos es muy versatil, se basa en las listas (un tipo de variable en python) y funciona así:

El bloque de código se ejecutará mientras no acabe de recorrer la lista. El valor de variable será el item de la lista que está siendo tratado en el momento. Ejemplo:

la función range retorna una lista de números según los parámetros de entrada: En este caso, range está generando una lista que va desde -9 hasta 9 (un número antes del segundo parámetro). La lista de números generada por range se representa así: [-9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9] El código de ejemplo imprimirá los números del -9 al 9. 

In [ ]:
i = 0
for i in range(-9, 10):
    print(i)

-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9


Usando la función for, escriba un código que imprima los números primos entre 100 y 200.

In [ ]:
s = 0
i=0
n=0

for i in range(100,201):
    esPrimo=True
    for n in range(2, i):
        if i%n == 0:
            esPrimo=False
    if esPrimo == True:
        s += i
            

print('la suma todos los numeros primos del 100 al 200 es',s)

la suma todos los numeros primos del 100 al 200 es 3167


#### Ejercicios

1.- Considera una pelota lanzada desde una torre de altura $h$ y con velocidad inicial cero. Escriba un programa que pregunte al usuario la altura de la torre y diga el tiempo que tardará en caer la pelota.

In [ ]:
from math import sqrt
g = 9.81

h = int(input('ingresa la altura de la torre en metros: '))

t = sqrt(2*h/g)

print('el tiempo que tarda la pelota en caer al piso desde la altura de', h, 'metros es de', t, 'segundos')

2.- Se lanzará un satelite para que realice una órbita circular alrededor de la tierra de manera tal que su periodo es de $T$ segundos.
- Encuentre una expresión para la altura a la cual debe estar el satelite. Considere $G=6.67\times 10^{-11}$ $m^{3}kg^{-1}s^{-2}$, la masa dela tierra $M=5.07\times 10^{24}$ $Kg$  y $R=6371$ $Km$ su radio. Escriba su resultado aquí, puede usar codigo latex (usando el marcador \$)

$h=\sqrt[3]{\frac{GMT^{2}}{4\pi^{2}}}-R$

- Escriba un programa que pregunte al usuario el valor deseado de $T$ y calcule e imprima la altura correcta en metros.

In [ ]:
import numpy as np
import math 

G = 6.67 * 10**-11 #m^3/kg*s^2
M = 5.07 * 10**24 #kg
R = 6371 * 10**3 #m

T = float(input('Ingrese el valor del periodo T en segundos: ')) 

h = (G*M * T**2 / (4 * math.pi**2))**(1/3) - R

if h == 0: 
    print('Para cumplir con el periodo de', T , 'segundos, el satelite deberia estar a la altura de la suerficie')
elif h < 0: 
    print('Cumplir con el periodo ingresado resulta imposile en las condiciones planteadas, prueba con un valor mas grande')
else:
    print('La altura de la orbita sobre la superficie terrestre es de', h, 'metros')


- Use su programa para calcular la altura de las órbitas geosincronas aquellas que realizan una vuelta en un día. 

h = 33617383.38027233 metros

- Use su programa para calcular la altura de una órbita de 90 minutos y una de 45 minutos. ¿Qué concluye de estos resultados? 

Cumplir con el periodo ingresado tanto de 90 como de 45 minutos resulta imposile en las condiciones planteadas.

- si es necesario usando condicionales para reescribir su programa.

In [ ]:
#ya los tiene, no es necesario

.

- Técnicamente un satelite geosíncrono es aquel que orbita la tierra una vez cada día sideral, que es 23.93 horas, no cada 24. ¿Porqué es esto? y ¿Qué diferencia daría esto en altitud?

- dia sideral  --> 33539590.34362398 metros
- dia 24 horas --> 33617383.38027233 metros

.

3.- Usando ciclos aproxime el valor de $\sqrt{3}$, usando la evaluación iterativa de la siguiente expresión $x=(x+3/x)/2$ iniciando con x=1. El código debe imprimir el valor en cada iteración. 

In [ ]:
x = 1
for i in range(7):
    x = (x + 3/x) / 2
    print(x)

2.0
1.75
1.7321428571428572
1.7320508100147274
1.7320508075688772
1.7320508075688772
1.7320508075688772


## 2.- Paquetes y modulos para matemáticas y matrices

Existen operaciones además de las aritméticas que vamos a necesitar en nuestras simulaciones, estas no están definidas defacto en python, sin embargo podemos usarlas si tan solo la importarmos del paquete y modulo apropiado. Por ejemplo supongamos que queremos calcular el error de nuestro cálculo de $\sqrt{3}$ en el ejercicio anterior. Entonces tendríamos que comparar nuestra aproximación con el cálculo de función intrínseca. 

Para usar la función para sacar raiz primero la importamos así

Modifique el ejercicio anterior para que imprima el error en cada iteracción con respecto a la función intrínseca de python.

In [ ]:
from math import sqrt

import numpy as np
x = 1 
while x != sqrt(3):
    x = (x + 3/x)/2
    print('valor aprox=', x, 'error:', abs( (sqrt(3) - x) / sqrt(3) )* 100 , '%')

valor aprox= 2.0 error: 15.47005383792516 %
valor aprox= 1.75 error: 1.0362971081845145 %
valor aprox= 1.7321428571428572 error: 0.005314484631615096 %
valor aprox= 1.7320508100147274 error: 1.4121122650442793e-07 %
valor aprox= 1.7320508075688772 error: 0.0 %


El paquete math contiene la mayoría de las funciones básicas incluyendo: log, log10, exp, sin, cos, tan, atan, acos, atan. sinh, cosh, tanh, sqrt, etc. Si quiere verlas todas, visite la siguiente dirección __(https://docs.python.org/2/library/math.html)__ . si se quiere importar todas las funciones de un modulo se usa la siguiente expresión.

Usemos estas funciones: Escriba un código que pregunte al usuario las coordenadas cartesianas $(x,y)$ y que arroje su representación en polares $(r,\theta)$. 

In [ ]:
from math import atan2, sqrt

print('ingresa las coordenadas cartesianas')
x= int(input('x = '))
y= int(input('y = '))

print('cartesianas:', (x,y))

r = sqrt(x**2 + y**2)
theta = atan2(y, x) #considera el signo

print('sus correspondientes coordenadas polares son:', (r,theta))


Escriba un código que hago la transformación inversa: pregunte al usuario la representación en polares $(r,\theta)$ y arroje las coordenadas cartesianas $(x,y)$. 

In [ ]:
from math import cos, sin, radians

print('ingresa las coordenadas polares')
r= int(input('r = '))
theta= int(input('theta = '))

print('polares', (x,y))


x = r * cos(radians(theta))
y = r * sin(radians(theta))

print('sus correspondientes coordenadas cartesianas son:', (x,y))

### Matrices

Las matrices las vamos a tratar usando el paquete numpy (numerical python), de manera general existe dos maneras de importar funciones, por ejemplo si queremos usar la función array, podemos hacer dos cosas:

O bien

Usando array defina un vector columna $Vc$ de dimensión 4, un vector renglon $Vr$ de dimension 5 y una matrix $A$ de 3x3 con valores cualesquiera.

In [4]:
import numpy as np 

In [5]:
Vc = np.array([[1], [2], [3], [4]])
Vr = np.array([1, 2, 3, 4, 5])
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


Defina otra matriz de 3x3 B, y aplique las funciones aritméticas básicas con la matriz A.

In [6]:
B = np.array([[5,9,3], [9, 7, 6], [2, 1, 3]])

#suma
C = A + B 
print('A+B = \n', C , '\n')
#resta
C = A - B
print('A-B = \n', C, '\n')
#producto de dos matrices
C = np.dot(A,B)
print('A*B = \n', C, '\n')
#producto escalar
C = 2 * A
print('2*A = \n', C, '\n')
#transpuesta 
C = A.T
print('transpuesta de A = \n', C, '\n')

A+B = 
 [[ 6 11  6]
 [13 12 12]
 [ 9  9 12]] 

A-B = 
 [[-4 -7  0]
 [-5 -2  0]
 [ 5  7  6]] 

A*B = 
 [[ 29  26  24]
 [ 77  77  60]
 [125 128  96]] 

2*A = 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

transpuesta de A = 
 [[1 4 7]
 [2 5 8]
 [3 6 9]] 



¿Cómo se accesa a los valores de la matriz? supongamos que se quiere extraer el elemento 1,3 de A ¿Cómo se hace? Averigue y reporte sus resultados


In [7]:
print(A, '\n')
print('elemento(1,3):', A[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

elemento(1,3): 3


se accede a los valores de la matriz de la siguiente manera: nombreMatriz[0,2]. En este ejemplo se accede al valor ubicado en el renglon 1 y columna 3, notese que, al igual que sucede con las listas, la enumeración de los elementos inicia desde el 0

IMPORTANTE: (1) seguro ya notó que la numeración de los arreglos va de 0 a N-1, con N el rango de la matriz. (2) cuando se usa la siguiente sentencia Matriz_A=MatrizB python no crea dos variables si no que la matriz_A se vuelve una referencia de matriz_B, esto se puede cambiar haciendo por ejemplo matriz_A=1.\*matriz_B o bien con la función copy.

## 3.- Definición de Funciones

Una función te permite definir un bloque de código reutilizable que se puede ejecutar muchas veces dentro de tu programa.Las funciones te permiten crear soluciones más modulares y si bien Python ya proporciona muchas funciones integradas como print() y len(), también puedes definir tus propias funciones para usar en tus proyectos.Una de las grandes ventajas de usar funciones en tu código es que reduce el número total de líneas de código en tu proyecto.

#### Sintaxis de las funciones

En Python, una definición de función tiene las siguientes características:


1.- La palabra clave def

2.- Un nombre de función

3.- Paréntesis ’()’, y dentro de los paréntesis los parámetros de entrada, aunque los parámetros de entrada sean opcionales.

4.- Dos puntos ’:’

5.- Algún bloque de código para ejecutar

6.- Una sentencia de retorno (opcional)

Ejemplo:

Define una función que se llame Primos e imprima los números primos del 1 al 100

In [8]:
def primos():

    for n in range(1, 101):
        es_primo = True

        if n > 1:

            for i in range(2, n):

                if (n % i) == 0:
                    es_primo = False
                    break
                
            if es_primo:
                print(n)

primos()

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


Define una función que se llame PrimosN que pregunte el rango de números en los que va a encontrar los números primos y que de como salida el número de primos encontrados

In [ ]:
def PrimosN():

    inicio = int(input('inicio:'))
    fin = int(input('fin:'))

    contador = 0
    for n in range(inicio, fin + 1):
        es_primo = True
        for i in range(2, n):
            if (n % i) == 0:
                es_primo = False
                break
        if es_primo:
            contador += 1
    return contador

print('cantidad de numeros primos:',PrimosN())

Define una funcion que se llame Mutl3p3 que tome de entrada dos matrices de 3x3 y de como salida la multiplicación de estas matrices.

In [9]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[5,9,3], [9, 7, 6], [2, 1, 3]])

In [10]:
def Mutl3p3(A,B):
    C = np.dot(A,B)
    return C

Mutl3p3(A,B)

array([[ 29,  26,  24],
       [ 77,  77,  60],
       [125, 128,  96]])

Defina una función que tome como entrada dos matrices A y B y que calcule el conmutador es decir AB-BA y arroje como salida el valor del resultado de la conmutación

In [11]:
def conmutador(A, B):
    C = np.dot(A,B) - np.dot(B,A)
    return C

conmutador(A,B)

array([[-33, -53, -72],
       [ -2, -24, -63],
       [ 98,  95,  57]])

### Programación orientada a objetos

Una de las características más importantes de python es que es un lenguaje orientado a objetos, para aprender sobre estas caráctieristicas, se invita a leer este artículo breve al respecto. https://aprendeconalf.es/docencia/python/manual/objetos/